version: '3.8'
services:
    #redis:
    # user: "${USER_ID}"
    #    image: redis:latest
    #    container_name: redis
    #    ports:
    #        - '6379:6379'
    #    networks:
    #        - services-network

    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - '5432:5432'
        env_file: .env.database
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - services-network

networks:
    services-network:
        driver: bridge
