version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - '5432:5432'
        env_file: .env.database
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - services-network

networks:
    services-network:
        driver: bridge
